name: Re-call Github Actions
on:
    push:
         branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: welcome
          run: echo "Vaa Arunachalum nee thirumba Varuva nu theriyum"